/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  omSidebar: [
    'intro',
    'architecture',
    'relationships',
  ],

  guiderSidebar: [
    {
      type: 'autogenerated',
      dirName: 'guider',
    },
  ],

  omRegelverketSidebar: [
    'forvaltning-och-synpunkter',
  ],
};

export default sidebars;
